---
- name: Prepare

  hosts: all

  gather_facts: false

  vars_files:
    - - 'vars/lsb-release/{{ ansible_distribution }}.yml'
      - 'vars/lsb-release/{{ ansible_os_family }}.yml'
      - 'vars/lsb-release/default.yml'

  tasks:

    - name: run setup script
      script: 'prepare.sh'
      environment:
        APT_DEBIAN_URI: '{{ aptsource_debian_uri }}'
        APT_DEBIAN_SECURITY_URI: '{{ aptsource_debian_security_uri }}'

    - name: bootstrap
      import_role:
        name: dochang.bootstrap

    - name: install lsb_release
      package:
        name: '{{ lsbrelease_package }}'
        state: present

    - name: regather facts from lsb_release
      setup:

    - name: config pypi index url
      ini_file:
        dest: '~/.config/pip/pip.conf'
        section: global
        option: index-url
        value: '{{ pip_index_url }}'
        state: present

    - import_role:
        name: dochang.pip

    - name: ensure /etc/docker present
      file:
        path: /etc/docker
        group: root
        owner: root
        mode: '700'
        state: directory

    - name: config dockerd
      copy:
        dest: '/etc/docker/daemon.json'
        content: "{{ dockerd_config | to_nice_json }}\n"
        group: root
        owner: root
        mode: '600'
